### PR TITLE
fix [#30]: Fix unsupported engine warning

### PR DESCRIPTION
**Pull request by pgerke**
## :recycle: Current situation

The issue is well described in https://github.com/homebridge/ciao/issues/30

## :bulb: Proposed solution

In the `package.json` file, change the `node` requirement in the `engines` element to allow all node version larger than or equal to Node 14.

## :gear: Release Notes

Fixed an issue with the node version requirements.

## :heavy_plus_sign: Additional Information
N/A

### Testing

The change only affects the `package.json`. No source code or tests were touched.

### Reviewer Nudging

The `package.json` 😉

### CODE REVIEW

**Comment by TA2k** [comment]
@Supereg Please merge this PR as soon as possible. Because the current 1.1.6 version is blocking all package with homebridge as dependency

**Comment by Supereg** [comment]
This PR includes more changes than what it describes.
Will fix the issue tonight though.

**Comment by pgerke** [comment]
The only changes besides the engines fix are a version number bump according to semver and the corresponding documentation update that was done by `npm run version`.

**Comment by TA2k** [comment]
Ok for me it looks like only the change and bump to 1.1.7

**Comment by Supereg** [comment]
v1.1.7 is live any minute now

**Pull request closed without merging**
